/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import CONTROLADOR.Controlador_Clientes;
import CONTROLADOR.ControladorAutomovil;
import CONTROLADOR.ControladorServicio;
import MODELO.Automovil;
import MODELO.Cliente;
import MODELO.Servicio;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author Anuar
 */
public class LavaAutosform extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LavaAutosform.class.getName());
    private final Controlador_Clientes controladorClientes = new Controlador_Clientes();
    private final ControladorAutomovil controladorAutomovil = new ControladorAutomovil();
    private final ControladorServicio controladorServicio = new ControladorServicio();

    /**
     * Creates new form LavaAutosform
     */
    public LavaAutosform() {
        initComponents();
        cargarClientesEnCombos();
        cargarHistorialServicios(controladorServicio.listarServicios());
        txtHora.setEditable(false);
        colocarHoraActual();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dcFechaRegistro = new com.toedter.calendar.JDateChooser();
        btnGuardarCliente = new javax.swing.JButton();
        btnLimpiarCliente = new javax.swing.JButton();
        pnlAutomovil = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2_seleccioneUnCliente = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3_tipo_auto = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPlacas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox4_EstadoDelAuto = new javax.swing.JComboBox<>();
        btnGuardarAutomovil = new javax.swing.JButton();
        btnLimpiarMenuAutomovil = new javax.swing.JButton();
        pnlServicio = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox5_SeleccioneUnCliente = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox6_SeleccioneUnAutomovil = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox7_TipoDeLavado = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        btnGuardarServicio = new javax.swing.JButton();
        btnLimpiarMenuServicio = new javax.swing.JButton();
        pnlHistorial = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscarHistorialDeServicios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnActualizarHistorialDeServicios = new javax.swing.JButton();
        btnLimpiarBusqueda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO DE CLIENTE");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO P:");

        jLabel4.setText("APELLIDO M:");

        txtApellidoM.addActionListener(this::txtApellidoMActionPerformed);

        jLabel5.setText("GENERO:");

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO", "NO BINARIO", " " }));
        cmbGenero.addActionListener(this::cmbGeneroActionPerformed);

        jLabel6.setText("TELEFONO:");

        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);

        jLabel7.setText("CORREO:");

        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        jLabel8.setText("CIUDAD:");

        jLabel9.setText("FECHA REGISTRO:");

        btnGuardarCliente.setText("GUARDAR");
        btnGuardarCliente.addActionListener(this::btnGuardarClienteActionPerformed);

        btnLimpiarCliente.setText("LIMPIAR");
        btnLimpiarCliente.addActionListener(this::btnLimpiarClienteActionPerformed);

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtApellidoM)))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtTelefono)
                            .addComponent(txtCiudad))
                        .addGap(74, 74, 74))))
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnGuardarCliente)
                        .addGap(58, 58, 58)
                        .addComponent(btnLimpiarCliente)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCliente)
                    .addComponent(btnLimpiarCliente))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("CLIENTE", pnlCliente);

        jLabel10.setText("REGISTRO DE AUTOMOVIL:");

        jLabel11.setText("CLIENTE:");

        jComboBox2_seleccioneUnCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente..." }));

        jLabel12.setText("TIPO:");

        jComboBox3_tipo_auto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEDAN", "SUV", "PICKUP", "HATCHBACK" }));

        jLabel13.setText("MARCA:");

        jLabel14.setText("MODELO:");

        jLabel15.setText("COLOR:");

        jLabel16.setText("PLACAS");

        jLabel17.setText("AÑO:");

        jLabel18.setText("ESTADO:");

        jComboBox4_EstadoDelAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EXCELENTE", "BUENO", "REGULAR", "MALO" }));

        btnGuardarAutomovil.setText("GUARDAR");
        btnGuardarAutomovil.addActionListener(this::btnGuardarAutomovilActionPerformed);

        btnLimpiarMenuAutomovil.setText("LIMPIAR");
        btnLimpiarMenuAutomovil.addActionListener(this::btnLimpiarMenuAutomovilActionPerformed);

        javax.swing.GroupLayout pnlAutomovilLayout = new javax.swing.GroupLayout(pnlAutomovil);
        pnlAutomovil.setLayout(pnlAutomovilLayout);
        pnlAutomovilLayout.setHorizontalGroup(
            pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutomovilLayout.createSequentialGroup()
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAutomovilLayout.createSequentialGroup()
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAutomovilLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2_seleccioneUnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnio))
                        .addGap(235, 235, 235)))
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutomovilLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(pnlAutomovilLayout.createSequentialGroup()
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox3_tipo_auto, 0, 131, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtPlacas)
                            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox4_EstadoDelAuto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71))))
            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnGuardarAutomovil)
                .addGap(45, 45, 45)
                .addComponent(btnLimpiarMenuAutomovil)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAutomovilLayout.setVerticalGroup(
            pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAutomovilLayout.createSequentialGroup()
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAutomovilLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2_seleccioneUnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3_tipo_auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAutomovilLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4_EstadoDelAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAutomovil)
                    .addComponent(btnLimpiarMenuAutomovil))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("AUTOMOVIL", pnlAutomovil);

        jLabel19.setText("REGISTRO DE SERVICIO");

        jLabel20.setText("CLIENTE:");

        jComboBox5_SeleccioneUnCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente..." }));
        jComboBox5_SeleccioneUnCliente.addActionListener(this::jComboBox5_SeleccioneUnClienteActionPerformed);

        jLabel21.setText("AUTOMOVIL:");

        jComboBox6_SeleccioneUnAutomovil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un automóvil..." }));

        jLabel22.setText("TIPO DE LAVADO:");

        jComboBox7_TipoDeLavado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAVADO BASICO", "LAVADO COMPLETO", "LAVADO PREMIUM", "ENCERADO" }));

        jLabel23.setText("PRECIO:");

        jLabel24.setText("FECHA DE SERVICIO:");

        jLabel25.setText("HORA:");

        txtHora.addActionListener(this::txtHoraActionPerformed);

        jLabel26.setText("OBSERVACIONES:");

        btnGuardarServicio.setText("GUARDAR");
        btnGuardarServicio.addActionListener(this::btnGuardarServicioActionPerformed);

        btnLimpiarMenuServicio.setText("LIMPIAR");
        btnLimpiarMenuServicio.addActionListener(this::btnLimpiarMenuServicioActionPerformed);

        javax.swing.GroupLayout pnlServicioLayout = new javax.swing.GroupLayout(pnlServicio);
        pnlServicio.setLayout(pnlServicioLayout);
        pnlServicioLayout.setHorizontalGroup(
            pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServicioLayout.createSequentialGroup()
                .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel19))
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox7_TipoDeLavado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5_SeleccioneUnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServicioLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServicioLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServicioLayout.createSequentialGroup()
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox6_SeleccioneUnAutomovil, 0, 1, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtHora))
                        .addGap(130, 130, 130))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlServicioLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(pnlServicioLayout.createSequentialGroup()
                .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel26))
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnGuardarServicio)
                        .addGap(87, 87, 87)
                        .addComponent(btnLimpiarMenuServicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlServicioLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        pnlServicioLayout.setVerticalGroup(
            pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlServicioLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5_SeleccioneUnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6_SeleccioneUnAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7_TipoDeLavado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnlServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarServicio)
                    .addComponent(btnLimpiarMenuServicio))
                .addGap(147, 147, 147))
        );

        tabPrincipal.addTab("SERVICIO", pnlServicio);

        jLabel27.setText("HISTORIAL DE SERVICIOS:");

        jLabel28.setText("BUSCAR:");

        btnBuscarHistorialDeServicios.setText("BUSCAR");
        btnBuscarHistorialDeServicios.addActionListener(this::btnBuscarHistorialDeServiciosActionPerformed);

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "AUTOMOVIL", "TIPO LAVADO", "FECHA", "HORA", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        btnActualizarHistorialDeServicios.setText("ACTUALIZAR");
        btnActualizarHistorialDeServicios.addActionListener(this::btnActualizarHistorialDeServiciosActionPerformed);

        btnLimpiarBusqueda.setText("LIMPIAR");
        btnLimpiarBusqueda.addActionListener(this::btnLimpiarBusquedaActionPerformed);

        javax.swing.GroupLayout pnlHistorialLayout = new javax.swing.GroupLayout(pnlHistorial);
        pnlHistorial.setLayout(pnlHistorialLayout);
        pnlHistorialLayout.setHorizontalGroup(
            pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistorialLayout.createSequentialGroup()
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHistorialLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel27))
                    .addGroup(pnlHistorialLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnActualizarHistorialDeServicios)
                        .addGap(57, 57, 57)
                        .addComponent(btnLimpiarBusqueda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistorialLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlHistorialLayout.createSequentialGroup()
                            .addComponent(txtBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarHistorialDeServicios))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        pnlHistorialLayout.setVerticalGroup(
            pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistorialLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHistorialDeServicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarHistorialDeServicios)
                    .addComponent(btnLimpiarBusqueda))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("HISTORIAL", pnlHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarClienteActionPerformed
       limpiarFormularioCliente();
    }//GEN-LAST:event_btnLimpiarClienteActionPerformed

    private void btnBuscarHistorialDeServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHistorialDeServiciosActionPerformed
         String textoBusqueda = txtBuscar.getText().trim();

    ArrayList<Servicio> encontrados =
            controladorServicio.buscarServicios(textoBusqueda);

    cargarHistorialServicios(encontrados);
    }//GEN-LAST:event_btnBuscarHistorialDeServiciosActionPerformed

    private void btnActualizarHistorialDeServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHistorialDeServiciosActionPerformed
            cargarHistorialServicios(controladorServicio.listarServicios());
    }//GEN-LAST:event_btnActualizarHistorialDeServiciosActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
     String nombre = txtNombre.getText().trim();
    String apellidoPaterno = txtApellidoP.getText().trim();
    String apellidoMaterno = txtApellidoM.getText().trim();

    Object seleccionGenero = cmbGenero.getSelectedItem();
    String genero = seleccionGenero == null ? "" : seleccionGenero.toString().trim();

    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();
    String ciudad = txtCiudad.getText().trim();
    Date fechaRegistro = dcFechaRegistro.getDate();

    if (nombre.isEmpty() || apellidoPaterno.isEmpty()
            || genero.isEmpty() || telefono.isEmpty()
            || fechaRegistro == null) {

        JOptionPane.showMessageDialog(
                this,
                "Completa nombre, apellido paterno, género, teléfono y fecha.",
                "Datos incompletos",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    boolean guardado = controladorClientes.guardarCliente(
            nombre,
            apellidoPaterno,
            apellidoMaterno,
            genero,
            telefono,
            correo,
            ciudad,
            fechaRegistro
    );

    if (guardado) {
        JOptionPane.showMessageDialog(
                this,
                "Cliente guardado correctamente.",
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioCliente();
        cargarClientesEnCombos();

    } else {
        JOptionPane.showMessageDialog(
                this,
                "No fue posible guardar el cliente.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void btnGuardarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAutomovilActionPerformed
    Cliente cliente = obtenerClienteSeleccionado(
            jComboBox2_seleccioneUnCliente
    );

    String tipo = jComboBox3_tipo_auto.getSelectedItem().toString();
    String marca = txtMarca.getText().trim();
    String modelo = txtModelo.getText().trim();
    String color = txtColor.getText().trim();
    String placas = txtPlacas.getText().trim();
    String estado = jComboBox4_EstadoDelAuto.getSelectedItem().toString();

    int anio;

    try {
        anio = Integer.parseInt(txtAnio.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "El año debe ser un número válido.",
                "Dato incorrecto",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (cliente == null) {
        JOptionPane.showMessageDialog(
                this,
                "Selecciona un cliente.",
                "Cliente requerido",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    boolean guardado = controladorAutomovil.guardarAutomovil(
            cliente,
            tipo,
            marca,
            modelo,
            color,
            placas,
            anio,
            estado
    );

    if (guardado) {
        JOptionPane.showMessageDialog(
                this,
                "Automóvil guardado correctamente.",
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioAutomovil();
        cargarAutomovilesServicio();

    } else {
        JOptionPane.showMessageDialog(
                this,
                "Revisa los datos. Las placas no pueden repetirse y el año debe ser válido.",
                "No se pudo guardar",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGuardarAutomovilActionPerformed

    private void btnLimpiarMenuAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMenuAutomovilActionPerformed
        limpiarFormularioAutomovil();
    }//GEN-LAST:event_btnLimpiarMenuAutomovilActionPerformed

    private void jComboBox5_SeleccioneUnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5_SeleccioneUnClienteActionPerformed
       cargarAutomovilesServicio();
    }//GEN-LAST:event_jComboBox5_SeleccioneUnClienteActionPerformed

    private void btnGuardarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarServicioActionPerformed
    Cliente cliente = obtenerClienteSeleccionado(
            jComboBox5_SeleccioneUnCliente
    );

    Automovil automovil = obtenerAutomovilSeleccionado();

    Object seleccionadoTipo = jComboBox7_TipoDeLavado.getSelectedItem();
    String tipoLavado = seleccionadoTipo == null
            ? ""
            : seleccionadoTipo.toString().trim();

    String textoPrecio = txtPrecio.getText().trim();
    colocarHoraActual();
String hora = txtHora.getText().trim();
    String observaciones = txtObservaciones.getText().trim();
    Date fechaServicio = jDateChooser2.getDate();

    if (cliente == null) {
        JOptionPane.showMessageDialog(
                this,
                "Selecciona un cliente.",
                "Cliente requerido",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (automovil == null) {
        JOptionPane.showMessageDialog(
                this,
                "Selecciona un automóvil.",
                "Automóvil requerido",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    if (fechaServicio == null) {
        JOptionPane.showMessageDialog(
                this,
                "Selecciona la fecha del servicio.",
                "Fecha requerida",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    double precio;

    try {
        precio = Double.parseDouble(textoPrecio);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "El precio debe ser un número válido.",
                "Precio incorrecto",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    boolean guardado = controladorServicio.guardarServicio(
            cliente,
            automovil,
            tipoLavado,
            precio,
            fechaServicio,
            hora,
            observaciones
    );

    if (guardado) {
        JOptionPane.showMessageDialog(
                this,
                "Servicio registrado correctamente.",
                "Registro exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarFormularioServicio();
        cargarHistorialServicios(controladorServicio.listarServicios());

    } else {
        JOptionPane.showMessageDialog(
                this,
                "Revisa los datos del servicio.",
                "No se pudo registrar",
                JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnGuardarServicioActionPerformed

    private void btnLimpiarMenuServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMenuServicioActionPerformed
    limpiarFormularioServicio();

    }//GEN-LAST:event_btnLimpiarMenuServicioActionPerformed

    private void btnLimpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBusquedaActionPerformed
        txtBuscar.setText("");
    cargarHistorialServicios(controladorServicio.listarServicios());
    }//GEN-LAST:event_btnLimpiarBusquedaActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Limpia el Menu de Clientes
    private void limpiarFormularioCliente() {
    txtNombre.setText("");
    txtApellidoP.setText("");
    txtApellidoM.setText("");
    cmbGenero.setSelectedIndex(-1);
    txtTelefono.setText("");
    txtCorreo.setText("");
    txtCiudad.setText("");
    dcFechaRegistro.setDate(null);

    txtNombre.requestFocus();
}
    
    //para cargar los clientes existentes en los combos
    private void cargarClientesEnCombos() {
    jComboBox2_seleccioneUnCliente.removeAllItems();
    jComboBox5_SeleccioneUnCliente.removeAllItems();

    jComboBox2_seleccioneUnCliente.addItem("Seleccione un cliente...");
    jComboBox5_SeleccioneUnCliente.addItem("Seleccione un cliente...");

    for (Cliente cliente : controladorClientes.listarClientes()) {
        String textoCliente = cliente.getIdCliente()
                + " - " + cliente.getNombreCompleto();

        jComboBox2_seleccioneUnCliente.addItem(textoCliente);
        jComboBox5_SeleccioneUnCliente.addItem(textoCliente);
    }
}
    //obtener clientes del combobox
    private Cliente obtenerClienteSeleccionado(
        javax.swing.JComboBox<String> combo) {

    Object seleccionado = combo.getSelectedItem();

    if (seleccionado == null) {
        return null;
    }

    String texto = seleccionado.toString();

    if (!texto.contains(" - ")) {
        return null;
    }

    try {
        int posicionSeparador = texto.indexOf(" - ");
        int idCliente = Integer.parseInt(
                texto.substring(0, posicionSeparador).trim()
        );

        return controladorClientes.buscarPorId(idCliente);

    } catch (NumberFormatException e) {
        return null;
    }
}

    private void limpiarFormularioAutomovil() {
    jComboBox2_seleccioneUnCliente.setSelectedIndex(0);
    jComboBox3_tipo_auto.setSelectedIndex(0);
    txtMarca.setText("");
    txtModelo.setText("");
    txtColor.setText("");
    txtPlacas.setText("");
    txtAnio.setText("");
    jComboBox4_EstadoDelAuto.setSelectedIndex(0);

    txtMarca.requestFocus();
}
    
    //caragar los autos de un cliente
    private void cargarAutomovilesServicio() {
    jComboBox6_SeleccioneUnAutomovil.removeAllItems();
    jComboBox6_SeleccioneUnAutomovil.addItem("Seleccione un automóvil...");

    Cliente cliente = obtenerClienteSeleccionado(
            jComboBox5_SeleccioneUnCliente
    );

    if (cliente == null) {
        return;
    }

    for (Automovil automovil : controladorAutomovil.listarPorCliente(cliente)) {
        String textoAutomovil = automovil.getIdAutomovil()
                + " - " + automovil.toString();

        jComboBox6_SeleccioneUnAutomovil.addItem(textoAutomovil);
    }
}
    
    
    private Automovil obtenerAutomovilSeleccionado() {
    Object seleccionado = jComboBox6_SeleccioneUnAutomovil.getSelectedItem();

    if (seleccionado == null) {
        return null;
    }

    String texto = seleccionado.toString();

    if (!texto.contains(" - ")) {
        return null;
    }

    try {
        int posicionSeparador = texto.indexOf(" - ");
        int idAutomovil = Integer.parseInt(
                texto.substring(0, posicionSeparador).trim()
        );

        return controladorAutomovil.buscarPorId(idAutomovil);

    } catch (NumberFormatException e) {
        return null;
    }
}
    
    
    private void limpiarFormularioServicio() {
    jComboBox5_SeleccioneUnCliente.setSelectedIndex(0);
    jComboBox6_SeleccioneUnAutomovil.setSelectedIndex(0);
    jComboBox7_TipoDeLavado.setSelectedIndex(0);

    txtPrecio.setText("");
    jDateChooser2.setDate(null);
    txtHora.setText("");
    txtObservaciones.setText("");

    txtPrecio.requestFocus();
}
    
    private void cargarHistorialServicios(ArrayList<Servicio> servicios) {
    DefaultTableModel modelo = (DefaultTableModel) tblHistorial.getModel();

    modelo.setRowCount(0);

    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

    for (Servicio servicio : servicios) {
        modelo.addRow(new Object[]{
            servicio.getIdServicio(),
            servicio.getCliente().getNombreCompleto(),
            servicio.getAutomovil().toString(),
            servicio.getTipoLavado(),
            formatoFecha.format(servicio.getFechaServicio()),
            servicio.getHora(),
            String.format("$%.2f", servicio.getPrecio())
        });
    }
}
    
    
    private void colocarHoraActual() {
    DateTimeFormatter formatoHora =
            DateTimeFormatter.ofPattern("HH:mm:ss");

    String horaActual = LocalTime.now().format(formatoHora);

    txtHora.setText(horaActual);
}
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LavaAutosform().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHistorialDeServicios;
    private javax.swing.JButton btnBuscarHistorialDeServicios;
    private javax.swing.JButton btnGuardarAutomovil;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarServicio;
    private javax.swing.JButton btnLimpiarBusqueda;
    private javax.swing.JButton btnLimpiarCliente;
    private javax.swing.JButton btnLimpiarMenuAutomovil;
    private javax.swing.JButton btnLimpiarMenuServicio;
    private javax.swing.JComboBox<String> cmbGenero;
    private com.toedter.calendar.JDateChooser dcFechaRegistro;
    private javax.swing.JComboBox<String> jComboBox2_seleccioneUnCliente;
    private javax.swing.JComboBox<String> jComboBox3_tipo_auto;
    private javax.swing.JComboBox<String> jComboBox4_EstadoDelAuto;
    private javax.swing.JComboBox<String> jComboBox5_SeleccioneUnCliente;
    private javax.swing.JComboBox<String> jComboBox6_SeleccioneUnAutomovil;
    private javax.swing.JComboBox<String> jComboBox7_TipoDeLavado;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAutomovil;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlHistorial;
    private javax.swing.JPanel pnlServicio;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPlacas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
